### ISSUE TITLE
Describe how to get/which zoning PDF's to load

### ISSUE THREAD

**Issue by kevinburke** [sid-kap/zoning-map-digitizer#1]
Where can I find a PDF to load into this project?

**Comment by sid-kap** [comment]
Yeah, I should probably add this to the README.
Here are some example files:

[Torrance, CA](https://www.torranceca.gov/home/showdocument?id=2784)
[Downey, CA](http://www.downeyca.org/civicax/filebank/blobdload.aspx?BlobID=5149)
[Cudahy, CA (not a pdf though)](http://www.cityofcudahy.com/uploads/5/3/9/9/53994499/zoning_map_1.5.bmp)
[Maywood, CA](https://evogov.s3.amazonaws.com/media/100/media/35931.pdf)
[Commerce, CA](http://www.ci.commerce.ca.us/DocumentCenter/Home/View/349)
[Pico Rivera, CA](http://www.pico-rivera.org/civicax/filebank/blobdload.aspx?blobid=2692)
[South Pasadena, CA](http://www.ci.south-pasadena.ca.us/modules/showdocument.aspx?documentid=192)
[Glendale, CA](http://www.glendaleca.gov/home/showdocument?id=654)
[Burbank, CA](http://www.burbankca.gov/home/showdocument?id=2620)
[Berkeley, CA](https://www.cityofberkeley.info/uploadedFiles/IT/Level_3_-_General/Zoning%20Map%2036x36%2020050120.pdf)

I've been mostly testing it with the Berkeley map. I've tried it on a handful of others, and it usually works, but the parameters might need to be tuned to work well on other maps.

**Comment by sid-kap** [comment]
Added these examples to the README
