### ISSUE TITLE
Explanatory landing page / demo

### ISSUE THREAD

**Issue by krpeacock** [sid-kap/zoning-map-digitizer#2]
In addition to building the tool, it might be worth creating a landing page to explain the purpose of the tool, give a brief explanation of how to use it, and to provide the user with some PDF's and an idea of where they can look to find their own compatible data sources

**Comment by sid-kap** [comment]
Yep, I agree!

**Comment by sid-kap** [comment]
@krpeacock Are you interested in contributing? I can answer any questions you have/give you an overview of what I've done and what needs to be done next.

**Comment by krpeacock** [comment]
Sorry, because of how crazy GitHub messages get at work, it's super easy
for comments like these to get lost. Mind switching to email for some back
and forth?

**Comment by sid-kap** [comment]
Sure! I'll send you an email
